### ISSUE TITLE
ESM Support

### ISSUE THREAD

**Issue by rubeniskov** [simoneb/fast-folder-size#102]
Currently there is not support for ESM Is there any plan to support it?

```
file:///<path>/post/index.js:3689
    __dirname,
    ^
ReferenceError: __dirname is not defined in ES module scope
This file is being treated as an ES module because it has a '.js' file extension and '/<path>/post/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
    at 145 (file:///<path>/post/index.js:3689:5)
    at __nccwpck_require__ (file:///<path>/post/index.js:[27](https://github.com/spazious/spazious-ui-dollhouse/actions/runs/9505368246/job/26204421506?pr=320#step:27:27)971:42)
    at 6482 (file:///<path>/post/index.js:3742:37)
    at __nccwpck_require__ (file:///<path>/post/index.js:27971:42)
    at file:///<path>/post/index.js:[28](https://github.com/spazious/spazious-ui-dollhouse/actions/runs/9505368246/job/26204421506?pr=320#step:27:28)036:12
    at file:///<path>/post/index.js:28233:3
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:123:5)
Node.js v20.13.1
```

**Comment by simoneb** [comment]
This is most likely a problem in your code, as ESM modules can use CJS modules without any issue. You are probably bundling this library, based on the stack trace you posted, and it's probably where the issue is coming from.

**Comment by rubeniskov** [comment]
Here you have a post with the error when using dirname in esm 

https://blog.logrocket.com/alternatives-dirname-node-js-es-modules/

**Comment by simoneb** [comment]
You're not seeing the actual issue I'm afraid. 

- In CJS, you can use __dirname
- In ESM, you cannot use __dirname
- In ESM, you can import CJS modules, and they can use __dirname
